apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-provider-user-deployment
  labels:
    app: microservice-provider-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-provider-user
  template:
    metadata:
      labels:
        app: microservice-provider-user
    spec:
      containers:
      - name: microservice-provider-user
        image: 99cloud/microservice-provider-user:latest
        ports:
        - containerPort: 8000
          protocol: TCP
        volumeMounts:
        - name: microservice-provider-user-config
          mountPath: /etc/microservice-provider-user/application.yml
          subPath: application.yml
      volumes:
      - name: microservice-provider-user-config
        configMap:
          name: microservice-provider-user-configmap
          items:
          - key: application.yml
            path: application.yml
      restartPolicy: Always
