apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-consumer-movie-configmap
  namespace: default
data:
  application.yml: |
    server:
      port: 8010
    spring:
      application:
        name: microservice-consumer-movie
    eureka:
      client:
        serviceUrl:
          defaultZone: https://example.org/eureka/ # Eureka服务URL
      instance:
        prefer-ip-address: true
